from __future__ import annotations

from typing import Final


ACCOUNTS_BILLING_SCHEMAS: Final[dict[str, tuple[str, ...]]] = {
    "USERS": (
        "user_id",
        "email",
        "display_name",
        "status",
        "created_at",
        "updated_at",
    ),
    "USER_CREDENTIALS": (
        "credential_id",
        "user_id",
        "password_hash",
        "status",
        "created_at",
        "updated_at",
    ),
    "STORY_CREDITS": (
        "credit_id",
        "user_id",
        "package_id",
        "payment_id",
        "status",
        "run_id",
        "created_at",
        "consumed_at",
        "revoked_at",
    ),
    "PAYMENT_ORDERS": (
        "payment_order_id",
        "user_id",
        "package_id",
        "product_id",
        "amount_cents",
        "currency",
        "provider",
        "provider_order_id",
        "external_reference",
        "idempotency_key",
        "status",
        "status_detail",
        "qr_code",
        "ticket_url",
        "created_at",
        "updated_at",
        "payer_email_normalized",
        "payment_mode",
        "validation_status",
        "approved_at",
    ),
    "PAYMENT_EVENTS": (
        "payment_event_id",
        "payment_order_id",
        "provider_order_id",
        "event_type",
        "status",
        "payload_json",
        "created_at",
    ),
    "WEBHOOK_EVENTS": (
        "webhook_event_id",
        "provider_event_id",
        "provider_order_id",
        "event_type",
        "signature_valid",
        "payload_json",
        "created_at",
    ),
}


RUNTIME_SCHEMAS: Final[dict[str, tuple[str, ...]]] = {
    "ROTEIROS": (
        "package_id",
        "script_version",
        "line_id",
        "order",
        "instruction",
        "status",
        "updated_at",
    ),
    "STORY_RUNS": (
        "run_id",
        "credit_id",
        "user_id",
        "package_id",
        "script_version",
        "current_block_id",
        "current_beat_id",
        "status",
        "ending_code",
        "state_version",
        "permanent_memory_ids_json",
        "started_at",
        "ended_at",
        "updated_at",
    ),
    "SESSIONS": (
        "session_id",
        "run_id",
        "user_id",
        "package_id",
        "instance_id",
        "status",
        "started_at",
        "last_seen_at",
        "ended_at",
    ),
    "INTERACTIONS": (
        "interaction_id",
        "session_id",
        "run_id",
        "user_id",
        "package_id",
        "sequence",
        "role",
        "speaker_id",
        "content",
        "block_id",
        "beat_id",
        "user_intent",
        "beat_consumed",
        "model",
        "input_tokens",
        "output_tokens",
        "latency_ms",
        "created_at",
        "metadata_json",
    ),
    "RUN_MEMORIES": (
        "run_memory_id",
        "run_id",
        "memory_id",
        "source_beat_id",
        "created_at",
    ),
}


EDITORIAL_SCHEMAS: Final[dict[str, tuple[str, ...]]] = {
    "STORIES": (
        "package_id",
        "script_version",
        "title",
        "introduction",
        "character_id",
        "first_block_id",
        "first_beat_id",
        "status",
        "updated_at",
    ),
    "CHARACTERS": (
        "package_id",
        "character_id",
        "name",
        "age",
        "physical_profile",
        "psychological_profile",
        "speech_style",
        "updated_at",
    ),
    "BLOCKS": (
        "package_id",
        "block_id",
        "order",
        "title",
        "entry_beat_id",
        "max_movements_per_response",
        "max_questions_per_response",
        "rules_json",
        "updated_at",
    ),
    "BEATS": (
        "package_id",
        "beat_id",
        "block_id",
        "order",
        "type",
        "required_movement",
        "canonical_line",
        "dramatic_direction",
        "next_beat_id",
        "max_questions",
        "max_sentences",
        "memory_writes_json",
        "allowed_transitions_json",
        "ending_json",
        "status",
        "updated_at",
    ),
    "MEMORIES": (
        "package_id",
        "memory_id",
        "memory_text",
        "source_beat_id",
        "status",
        "updated_at",
    ),
}
